spring:
  application:
    name: chitchat-monitor
  security: # 配置登录用户名和密码
    user:
      name: chitchat
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
  profiles:
    active: loc
server:
  port: 7006
